language: node_js

os:
  - linux
  - osx

node_js:
  - 4
  - 5
  - 6
  - 7
script: ./node_modules/mocha/bin/mocha tests/*.test.js
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start